export const site = {
  name: "Get Big Rig Insurance",
  legalName: "Vantage Point Risk Partners LLC",
  url: "https://getbigriginsurance.com",
  phone: "541-681-8793",
  phoneHref: "tel:+15416818793",
  phoneCTA: "Call or text 541-681-8793",
  email: "richard@vantagepointrisk.com",
  emailHref: "mailto:richard@vantagepointrisk.com",
  quotePath: "/get-a-quote",
  serviceArea: "Serving AZ, CA, CO, ID, MT, NM, NV, OR, TX, UT, WA & WY",
  serviceStates: ["AZ", "CA", "CO", "ID", "MT", "NM", "NV", "OR", "TX", "UT", "WA", "WY"],
  carrierCount: "23+",
  description:
    "Trucking insurance for new authorities and owner operators. We shop 23+ carriers to find the right coverage at a fair rate. Same-day coverage available.",
  parentSiteUrl: "https://www.vantagepointrisk.com/business/commercial-trucking-insurance/",
  nav: [
    { label: "New Authority", href: "/new-authority" },
    { label: "Owner Operator", href: "/owner-operator" },
    { label: "Cost", href: "/how-much-does-trucking-insurance-cost" },
    { label: "FAQ", href: "/faq" },
    { label: "About", href: "/about" },
    { label: "Blog", href: "/blog" },
  ],
};
